title: Crypto Shibe
description: The latest in the cryptocurrency culture and markets. Emphasis is on Dogecoin followed by Bitcoin but will also cover many other currencies and topics.
markdown: redcarpet
pygments: true
exclude:
  - README.md
  - Procfile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - todo.md
gzip: true
permalink: /:year/:month/:day/:title/

tag_dir: tags
