title: Crypto Shibe
description: The latest in the cryptocurrency culture and markets. Emphasis is on Dogecoin followed by Bitcoin but will also cover many other currencies and topics.
baseurl: http://cryptoshibe.com
markdown: redcarpet
pygments: true
exclude:
  - README.md
  - Procfile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - todo.md
gzip: true
permalink: /:year/:month/:day/:title/

tag_dir: tags

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
    - "/s3_website.yml"
    - "/thank-you/*"
  include_posts:
    - "/index.html"
